### ISSUE TITLE
Application not working after upgrading plaid_flutter from 3.1.8 to 5.0.3

### ISSUE THREAD

**Issue by ammarbhatkar90p-prog** [jorgefspereira/plaid_flutter#164]
My application was crashing as soon as i was opening the plaid brokarages it was only happening when the app was downloaded from appstore or playstore 

in order to overcome this issue i updated the flutter_plaid library but now the apk is not working in debig mode also and iam getting error 

Local\Pub\Cache\hosted\pub.dev\plaid_flutter-5.0.3\android\src\main\java\com\github\jorgefspereira\plaid_flutter\PlaidFlutterPlugin.java:243: error: no suitable constructor found for SubmissionData(String)
      SubmissionData submissionData = new SubmissionData(phoneNumber);
                                      ^
    constructor SubmissionData.SubmissionData(String,String) is not applicable
      (actual and formal argument lists differ in length)
    constructor SubmissionData.SubmissionData() is not applicable
      (actual and formal argument lists differ in length)
1 error

PLEASE RESPOND AND SEND AN ACKNOWLEGEMENT ASAP!

**Comment by techouse** [comment]
@ammarbhatkar90p-prog just pin your app to use v5.0.1

**Comment by techouse** [comment]
> 5.0.1 is alos not working getting same error during compile time

It compiles just fine here. Have you tried cleaning your build folder?

**Comment by ammarbhatkar90p-prog** [comment]
yes , i cleaned my build folder even tried by cleaning pub cache still not working
